BOT_NAME = "girivinity_crawler"
SPIDER_MODULES = ["app.crawler.spiders"]
NEWSPIDER_MODULE = "app.crawler.spiders"
ROBOTSTXT_OBEY = True
CONCURRENT_REQUESTS = 32
DOWNLOAD_TIMEOUT = 15
DEPTH_LIMIT = 2
REQUEST_FINGERPRINTER_IMPLEMENTATION = "2.7"
